//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaPresentacioAdmi
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistorialServicios
    {
        public int id_historial { get; set; }
        public int id_solicitud { get; set; }
        public Nullable<int> id_proveedor { get; set; }
        public string estadoProgreso { get; set; }
        public Nullable<System.DateTime> fecha_cambio { get; set; }
        public string comentario { get; set; }
        public string estado { get; set; }
    
        public virtual ProveedorServicio ProveedorServicio { get; set; }
        public virtual Solicitudes Solicitudes { get; set; }
    }
}
