//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaPresentacioAdmi
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProveedorServicio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProveedorServicio()
        {
            this.HistorialServicios = new HashSet<HistorialServicios>();
            this.ProveedorEtiqueta = new HashSet<ProveedorEtiqueta>();
            this.Solicitudes = new HashSet<Solicitudes>();
        }
    
        public int id_proveedor { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public int id_especializacion { get; set; }
        public string descripcion_perfil { get; set; }
        public string disponibilidad { get; set; }
        public Nullable<decimal> calificacion_promedio { get; set; }
        public Nullable<decimal> latitud { get; set; }
        public Nullable<decimal> longitud { get; set; }
        public string direccion { get; set; }
        public Nullable<System.DateTime> fecha_Registro { get; set; }
        public Nullable<System.DateTime> fecha_Nacimiento { get; set; }
        public string correo { get; set; }
        public string telefono { get; set; }
        public string sexo { get; set; }
        public string estado { get; set; }
    
        public virtual Especializaciones Especializaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistorialServicios> HistorialServicios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProveedorEtiqueta> ProveedorEtiqueta { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Solicitudes> Solicitudes { get; set; }
    }
}
