//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaPresentacioAdmi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solicitante
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Solicitante()
        {
            this.Solicitudes = new HashSet<Solicitudes>();
        }
    
        public int id_solicitante { get; set; }
        public string nombre_completo { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public string direccion { get; set; }
        public Nullable<System.DateTime> fecha_Registro { get; set; }
        public Nullable<System.DateTime> fecha_Nacimiento { get; set; }
        public string correo { get; set; }
        public string telefono { get; set; }
        public string sexo { get; set; }
        public string estado { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Solicitudes> Solicitudes { get; set; }
    }
}
