//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaPresentacioAdmi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solicitudes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Solicitudes()
        {
            this.HistorialServicios = new HashSet<HistorialServicios>();
        }
    
        public int id_solicitud { get; set; }
        public Nullable<int> id_solicitante { get; set; }
        public Nullable<int> id_servicio { get; set; }
        public Nullable<int> id_proveedor { get; set; }
        public Nullable<System.DateTime> fecha_solicitud { get; set; }
        public System.DateTime fecha_servicio { get; set; }
        public string estado { get; set; }
        public string detalles { get; set; }
        public string direccion_servicio { get; set; }
        public string metodo_pago { get; set; }
        public Nullable<decimal> costo { get; set; }
        public Nullable<int> calificacion { get; set; }
        public string comentario_calificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistorialServicios> HistorialServicios { get; set; }
        public virtual ProveedorServicio ProveedorServicio { get; set; }
        public virtual Servicios Servicios { get; set; }
        public virtual Solicitante Solicitante { get; set; }
    }
}
